server:
  port: 8080
  servlet:
    context-path: /chat
  address: 192.168.0.106


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chat_server?allowPublicKeyRetrieval=true&useSSL=true&serverTimezone=GMT
    username: root
    password: 12345

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.gohb.pojo


# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 192.168.91.155:22122